---
output: github_document
always_allow_html: yes
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "tools/readme/README-"
)
```

# ghnet

Tidied Github commit data + ggraph network plots

## Installation

```{r gh-installation, eval = FALSE}

remotes::install_github('yonicd/ghnet')

```

## Examples

```{r example}
library(ghnet,warn.conflicts = FALSE,quietly = TRUE)
```
 
 
### Fetch Commit Data

Work with the nibble using tidyverse just like a `data_frame`

```{r,eval=FALSE}
repos <- c(
'thinkr-open/remedy',
'hrbrmstr/slackr',
'hrbrmstr/ggalt',
'hrbrmstr/hrbrthemes',
'metrumresearchgroup/sinew')


#single
gh_data <- repos[1]%>%
  gh_commit_data()

#multiple
gh_data <- repos%>%
  purrr::map_df(gh_commit_data)

```

```{r}
gh_data
```
 
 
### Network Plots

```{r,fig.width=15,fig.ext='svg'}
gh_data%>%
  gh_plots(title = 'Github Repository Contribution Network')

gh_data%>%
  gh_plots(title = 'Github Repository Contribution Network',
           add_labels='user')

gh_data%>%
  gh_plots(title = 'Github Repository Contribution Network',
           add_labels='repo')

gh_data%>%
  dplyr::filter(date>=as.Date('2017-01-01'))%>%
  gh_plots(title = 'Github Repository Contribution Network',
           add_labels='both')
```